services:
  postgres:
    image: pgvector/pgvector:pg18-trixie
    container_name: ai_chat_postgres
    ports:
      - 5433:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  postgres_test:
    image: pgvector/pgvector:pg18-trixie
    container_name: ai_chat_postgres_test
    ports:
      - 5434:5432
    env_file:
      - .env.test
    volumes:
      - postgres_data_test:/var/lib/postgresql/data
      - ./src/data/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  postgres_data:
  postgres_data_test:
